# BUG: Does not work due to lack of OpenGL support on GitHub Actions
# Not using this workflow for now
name: Build desktop app
on:
  push:
    branches:
      - None

jobs:
  build-windows:
    name: Build windows app
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt pyinstaller
      - name: Build app
        run: |
          cd ${{github.workspace}}
          echo ${{secrets.WEB_API_KEY}} >> api_key.txt
          python copy_kv_files.py
          pyinstaller passlock_windows.spec
          mv dist/passlock passlock/
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: passlock
          filename: passlock.zip
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: passlock
          path: passlock.zip
