name: Build desktop app

on:
  push:
    branches: none

jobs:
  build-linux:
    name: Build linux app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get install libmtdev1
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build app
        run: |
          cd ${{github.workspace}}
          echo ${{secrets.WEB_API_KEY}} >> api_key.txt
          python copy_kv_files.py
          pyinstaller passlock_linux.spec
          mv dist/passlock passlock/
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: passlock
          filename: passlock.zip
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: passlock
          path: passlock.zip